version: '3.7'
services:
  jenkins:
    image: 'eu.gcr.io/tjth/jenkins-server:2.13'
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - '/data/jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './build-scripts:/scripts'
      - './config/git-config:/etc/gitconfig'
    env_file: 
      - jenkins.env
    container_name: jenkins
    restart: always