apiVersion: v1
kind: Service
metadata:
  name: svc-jenkins-web
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  - port: 8443
    name: https
  - port: 50000
    name: jenkins-agent
  selector:
    app: jenkins